[package]
name = "nodejs"
version = "0.1.0"
authors = ["patr0nus <dk4rest@gmail.com>"]
edition = "2018"

[patch.crates-io]
neon = { git = 'https://github.com/patr0nus/neon', branch = "napi-embedding" }

[features]
no-intl = []

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
napi-sys = { version = "1", features = [ "napi6" ]}
neon = { version = "0.7.1-napi", default-features = false, features = [ "napi-6", "event-queue-api",  "try-catch-api", "napi-embedding" ] }
once_cell = "1"
paste = "1"

[dev-dependencies]
anyhow = "1"

[build-dependencies]
reqwest = { version = "0.11", features = [ "blocking" ] }
anyhow = "1"
sha-1 = "0.9"
hex = "0.4"
zip-extract = "0.1"
once_cell = "1"
strum = { version = "0.20", features = [ "derive" ] }
