name: Lint

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '**/README.md'
      - 'libnode/**'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - '**/README.md'
      - 'libnode/**'

env:
  CARGO_TERM_COLOR: always

jobs:
  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Rust Cache
        uses: Swatinem/rust-cache@v2.7.3
        with:
          key: clippy
      - name: Check format
        run: cargo fmt --all -- --check
      - name: Clippy
        run: cargo clippy --all-targets -- -D warnings
