name: Publish

on:
  workflow_dispatch:
    inputs:
      bumplevel:
        description: cargo-release bump level
        required: true
        default: 'release'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: cargo release
      working-directory: nodejs
      run: |
        git config --global user.email "dk4rest@gmail.com"
        git config --global user.name "patr0nus"
        cargo install --version=~0.18 cargo-release
        echo cargo release -v ${{ github.event.inputs.bumplevel }} --execute --no-confirm
        cargo release -v ${{ github.event.inputs.bumplevel }} --execute --no-confirm --token ${{ secrets.CARGO_REGISTRY_TOKEN }}
