name: Test

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '**/README.md'
      - 'libnode/**'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - '**/README.md'
      - 'libnode/**'
env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    continue-on-error: true
    strategy:
      matrix:
        target: [
            x86_64-apple-darwin,
            aarch64-apple-darwin,
            x86_64-unknown-linux-gnu,
            x86_64-pc-windows-msvc
            #i686-pc-windows-msvc
        ]
        features: [ "", "full-icu" ]
        include:
          - target: x86_64-apple-darwin
            os: macos-13
          - target: aarch64-apple-darwin
            os: macos-13
            cargo_test_args: "--no-run"
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-22.04
          - target: x86_64-pc-windows-msvc
            os: windows-2022
          #- target: i686-pc-windows-msvc
          #  os: windows-2022
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - name: Run tests
      env:
        RS_NODEJS_CARGO_FEATURES: ${{ matrix.features }}
        RS_NODEJS_CARGO_TARGET: ${{ matrix.target }}
        RS_NODEJS_CARGO_TEST_ARGS: ${{ matrix.cargo_test_args }}
      shell: bash
      run: |
        rustup target add $RS_NODEJS_CARGO_TARGET
        cargo test --verbose --release $RS_NODEJS_CARGO_TEST_ARGS --target $RS_NODEJS_CARGO_TARGET --features "$RS_NODEJS_CARGO_FEATURES"
